"use client";

import { useCallback, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import {
  Bot,
  BrainCircuit,
  Command,
  Gauge,
  Loader2,
  PanelTop,
  PlugZap,
  Radar,
  Rocket,
  Sparkles,
  Workflow
} from "lucide-react";
import { ToolCard } from "@/components/tool-card";
import { cn } from "@/lib/utils";

type StageStatus = "pending" | "active" | "complete";

type Stage = {
  id: string;
  label: string;
  description: string;
  duration: number;
  output: (context: SimulationContext) => string;
};

type SimulationContext = {
  mission: string;
  objective: string;
  tools: string[];
  complexity: number;
};

type MissionLog = {
  id: string;
  mission: string;
  objective: string;
  tools: string[];
  result: string;
  duration: number;
};

const TOOL_LIBRARY = [
  {
    id: "plan",
    name: "Vector Strategist",
    description:
      "Breaks ambiguous goals into atomic actions with dependency-aware flow control.",
    focus: "Planning",
    capabilities: ["Goal graphing", "Risk mapping", "Success criteria"],
    accent: "linear-gradient(135deg, rgba(56, 189, 248, 0.5), rgba(59, 130, 246, 0.55))"
  },
  {
    id: "orchestrate",
    name: "Tool Orchestrator",
    description:
      "Renders the tool-chain playbook and routes calls with adaptive failure recovery.",
    focus: "Orchestration",
    capabilities: ["Tool scoring", "Auto fallback", "Parallel batching"],
    accent: "linear-gradient(135deg, rgba(96, 165, 250, 0.55), rgba(129, 140, 248, 0.55))"
  },
  {
    id: "research",
    name: "Context Retriever",
    description:
      "Harvests multi-source intelligence and crafts compressed knowledge packets.",
    focus: "Discovery",
    capabilities: ["Web scan", "Doc memory", "Signal ranking"],
    accent: "linear-gradient(135deg, rgba(45, 212, 191, 0.45), rgba(56, 189, 248, 0.45))"
  },
  {
    id: "code",
    name: "Synthesis Engineer",
    description:
      "Builds and verifies production-grade code artifacts with explainability baked in.",
    focus: "Production",
    capabilities: ["Type-safe output", "Test harnesses", "Diff reasoning"],
    accent: "linear-gradient(135deg, rgba(250, 204, 21, 0.45), rgba(248, 113, 113, 0.45))"
  },
  {
    id: "qa",
    name: "Quality Sentinel",
    description:
      "Validates acceptance criteria, regression risks, and alignment against the mission brief.",
    focus: "Assurance",
    capabilities: ["Spec matching", "Risk alerts", "Roll-back report"],
    accent: "linear-gradient(135deg, rgba(167, 139, 250, 0.45), rgba(236, 72, 153, 0.4))"
  }
];

const STAGES: Stage[] = [
  {
    id: "analysis",
    label: "Cognitive Mapping",
    description:
      "Interpreting the mission, identifying constraints, and exploring hidden dependencies.",
    duration: 1200,
    output: ({ objective, tools }) =>
      `Mapped mission context, discovered ${tools.length} capable tool${
        tools.length === 1 ? "" : "s"
      }, and defined the primary objective: ${objective.trim()}.`
  },
  {
    id: "planning",
    label: "Plan Assembly",
    description:
      "Composing the work graph, allocating tool responsibilities, and sequencing calls.",
    duration: 900,
    output: ({ tools, complexity }) =>
      `Built execution graph with ${Math.max(
        3,
        Math.round(complexity / 10)
      )} stages, leveraging ${tools.slice(0, 3).join(", ")} as core operators.`
  },
  {
    id: "execution",
    label: "Live Orchestration",
    description:
      "Running tool calls, capturing intermediate outputs, and recovering from faults in-flight.",
    duration: 1500,
    output: ({ tools, mission }) => {
      const primaryTools =
        tools.length > 0 ? tools.slice(0, 2).join(", ") : "core runtime primitives";
      return `Executed orchestrated run for "${mission}" using ${primaryTools}. All critical paths completed with adaptive retries.`;
    }
  },
  {
    id: "validation",
    label: "Outcome Validation",
    description:
      "Scoring deliverables against constraints, generating audit logs, and packaging insights.",
    duration: 800,
    output: ({ mission, complexity }) =>
      `Generated validation dossier with confidence ${Math.min(
        95,
        65 + complexity / 3
      )}%. Mission "${mission}" marked ready for hand-off.`
  }
];

const HERO_METRICS = [
  {
    label: "Latency Reduction",
    value: "42%",
    description: "Average time saved per mission compared to manual tool chains."
  },
  {
    label: "Auto Recovery",
    value: "98%",
    description: "Automatic rollback + retry coverage across execution failures."
  },
  {
    label: "Governed Actions",
    value: "12k",
    description: "Fully auditable actions generated by autonomous agents."
  }
];

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export default function Page() {
  const [mission, setMission] = useState("");
  const [objective, setObjective] = useState("");
  const [complexity, setComplexity] = useState(45);
  const [selectedTools, setSelectedTools] = useState<string[]>(["plan", "orchestrate"]);
  const [stageStates, setStageStates] = useState<Record<string, StageStatus>>(() =>
    STAGES.reduce(
      (acc, stage) => ({
        ...acc,
        [stage.id]: "pending" as StageStatus
      }),
      {}
    )
  );
  const [stageOutputs, setStageOutputs] = useState<Record<string, string>>({});
  const [isRunning, setIsRunning] = useState(false);
  const [missionLog, setMissionLog] = useState<MissionLog[]>([]);
  const [error, setError] = useState<string | null>(null);

  const availableTools = useMemo(
    () =>
      TOOL_LIBRARY.map((tool) => ({
        ...tool,
        isActive: selectedTools.includes(tool.id)
      })),
    [selectedTools]
  );

  const simulationContext = useMemo<SimulationContext>(
    () => ({
      mission: mission || "Untitled Mission",
      objective:
        objective ||
        "Draft missing objective. Using adaptive heuristics to maintain momentum.",
      tools: selectedTools,
      complexity
    }),
    [mission, objective, selectedTools, complexity]
  );

  const resetStages = useCallback(() => {
    const initial = STAGES.reduce(
      (acc, stage) => ({
        ...acc,
        [stage.id]: "pending" as StageStatus
      }),
      {}
    );
    setStageStates(initial);
    setStageOutputs({});
  }, []);

  const toggleTool = useCallback((toolId: string) => {
    setSelectedTools((prev) => {
      if (prev.includes(toolId)) {
        return prev.filter((item) => item !== toolId);
      }
      return [...prev, toolId];
    });
  }, []);

  const handleLaunch = useCallback(async () => {
    if (isRunning) return;
    if (!mission.trim() || !objective.trim()) {
      setError("A mission name and objective are required before launch.");
      return;
    }
    if (selectedTools.length === 0) {
      setError("Select at least one tool agent to deploy.");
      return;
    }
    setError(null);
    setIsRunning(true);
    resetStages();
    const runId = crypto.randomUUID();
    const startedAt = Date.now();

    for (const stage of STAGES) {
      setStageStates((prev) => ({ ...prev, [stage.id]: "active" }));
      setStageOutputs((prev) => ({
        ...prev,
        [stage.id]: `▶ ${stage.description}`
      }));
      await sleep(stage.duration * 0.35);
      setStageOutputs((prev) => ({
        ...prev,
        [stage.id]: stage.output(simulationContext)
      }));
      setStageStates((prev) => ({ ...prev, [stage.id]: "complete" }));
      await sleep(180);
    }

    const duration = Date.now() - startedAt;
    const summary = STAGES.map((stage) => stage.output(simulationContext)).join(" ");

    setMissionLog((prev) => [
      {
        id: runId,
        mission: simulationContext.mission,
        objective: simulationContext.objective,
        tools: [...simulationContext.tools],
        result: summary,
        duration
      },
      ...prev
    ]);

    setIsRunning(false);
  }, [isRunning, mission, objective, resetStages, selectedTools, simulationContext]);

  return (
    <main className="min-h-screen pb-20">
      <div className="mx-auto flex w-full max-w-7xl flex-col gap-12 px-6 pt-16">
        <header className="grid gap-8 md:grid-cols-[2fr,1fr] md:items-center">
          <div className="space-y-7">
            <span className="inline-flex items-center gap-2 rounded-full border border-sky-500/30 bg-slate-900/70 px-4 py-1 text-xs font-semibold uppercase tracking-[0.3em] text-sky-200">
              <Sparkles className="h-4 w-4" /> Autonomous Orchestration
            </span>
            <h1 className="text-4xl font-semibold leading-tight text-slate-50 md:text-5xl">
              Deploy multi-tool AI agents that plan, orchestrate, and deliver outcomes.
            </h1>
            <p className="max-w-2xl text-base text-slate-300/80 md:text-lg">
              Design the mission, select specialized operators, and simulate an end-to-end
              execution loop. Observe how the agent decomposes goals, routes tool calls,
              and governs delivery—all from a single cockpit.
            </p>
            <div className="flex flex-wrap gap-5">
              {HERO_METRICS.map((metric) => (
                <div
                  key={metric.label}
                  className="rounded-2xl border border-sky-500/20 bg-slate-900/50 px-5 py-4"
                >
                  <p className="text-3xl font-semibold text-sky-200">{metric.value}</p>
                  <p className="text-xs uppercase tracking-[0.35em] text-slate-400">
                    {metric.label}
                  </p>
                  <p className="mt-2 text-xs text-slate-400/80">{metric.description}</p>
                </div>
              ))}
            </div>
          </div>
          <div className="space-y-4 rounded-3xl border border-sky-500/20 bg-slate-900/60 p-6">
            <div className="flex items-center gap-3">
              <div className="grid h-12 w-12 place-items-center rounded-2xl bg-sky-500/20 text-sky-200">
                <Rocket className="h-7 w-7" />
              </div>
              <div>
                <p className="text-xs uppercase tracking-[0.4em] text-slate-400">
                  Launch Checklist
                </p>
                <p className="text-base font-semibold text-slate-100">
                  Mission control ready
                </p>
              </div>
            </div>
            <ul className="space-y-3 text-sm text-slate-300/90">
              <li className="flex items-center gap-2">
                <Command className="h-4 w-4 text-sky-300" />
                Draft your mission (§ Objective)
              </li>
              <li className="flex items-center gap-2">
                <PlugZap className="h-4 w-4 text-sky-300" />
                Activate the operators you need
              </li>
              <li className="flex items-center gap-2">
                <Radar className="h-4 w-4 text-sky-300" />
                Run the simulation and inspect telemetry
              </li>
            </ul>
          </div>
        </header>

        <section className="grid gap-8 lg:grid-cols-[1.85fr,1fr]">
          <div className="flex flex-col gap-8 rounded-3xl border border-sky-500/20 bg-slate-900/60 p-8">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs uppercase tracking-[0.35em] text-slate-400">
                  Mission Designer
                </p>
                <h2 className="text-2xl font-semibold text-slate-50">
                  Set the mission you want the agent to conquer
                </h2>
              </div>
              <Gauge className="h-8 w-8 text-sky-300" />
            </div>

            <div className="space-y-6">
              <div className="grid gap-5 md:grid-cols-2">
                <label className="flex flex-col gap-2">
                  <span className="text-sm font-semibold text-slate-200">
                    Mission Name
                  </span>
                  <input
                    value={mission}
                    onChange={(event) => setMission(event.target.value)}
                    placeholder="Launch adaptive knowledge base"
                    className="rounded-2xl border border-slate-700/60 bg-slate-900/80 px-4 py-3 text-sm text-slate-200 outline-none transition focus:border-sky-500 focus:shadow-focus"
                  />
                </label>

                <label className="flex flex-col gap-2">
                  <span className="text-sm font-semibold text-slate-200">
                    Complexity Index
                  </span>
                  <div className="rounded-2xl border border-slate-700/60 bg-slate-900/80 px-4 py-4">
                    <div className="flex items-center justify-between text-xs text-slate-400">
                      <span>Operational</span>
                      <span className="text-sky-300">{complexity}</span>
                      <span>Strategic</span>
                    </div>
                    <input
                      type="range"
                      min={10}
                      max={100}
                      value={complexity}
                      onChange={(event) => setComplexity(Number(event.target.value))}
                      className="mt-3 w-full accent-sky-400"
                    />
                  </div>
                </label>
              </div>

              <label className="flex flex-col gap-2">
                <span className="text-sm font-semibold text-slate-200">
                  Objective Narrative
                </span>
                <textarea
                  value={objective}
                  onChange={(event) => setObjective(event.target.value)}
                  placeholder="Describe the desired outcome, constraints, or artifacts to deliver."
                  rows={4}
                  className="resize-none rounded-2xl border border-slate-700/60 bg-slate-900/80 px-4 py-3 text-sm text-slate-200 outline-none transition focus:border-sky-500 focus:shadow-focus"
                />
              </label>
            </div>
          </div>

          <div className="flex h-full flex-col gap-6 rounded-3xl border border-sky-500/20 bg-slate-900/60 p-8">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs uppercase tracking-[0.35em] text-slate-400">
                  Run Controls
                </p>
                <h2 className="text-2xl font-semibold text-slate-50">
                  Execute the autonomous loop
                </h2>
              </div>
              <Workflow className="h-8 w-8 text-sky-300" />
            </div>
            <div className="flex flex-1 flex-col justify-between gap-6">
              <div className="rounded-2xl border border-sky-500/20 bg-slate-900/90 px-5 py-4 text-sm text-slate-300/90">
                <p>
                  The agent will iterate across four stages: cognitive mapping, plan
                  assembly, live orchestration, and validation. Telemetry streams live as
                  each stage completes.
                </p>
              </div>
              <button
                onClick={handleLaunch}
                className={cn(
                  "group flex items-center justify-center gap-3 rounded-2xl border border-sky-400/30 px-6 py-4 text-sm font-semibold uppercase tracking-[0.3em] transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-400/80",
                  isRunning
                    ? "cursor-not-allowed bg-slate-800/60 text-sky-200/70"
                    : "bg-gradient-to-r from-sky-500/80 via-blue-500/80 to-cyan-500/80 text-slate-950 shadow-lg shadow-sky-500/20 hover:scale-[1.01]"
                )}
              >
                {isRunning ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Running Simulation
                  </>
                ) : (
                  <>
                    <Rocket className="h-4 w-4 transition group-hover:translate-x-1" />
                    Launch Mission
                  </>
                )}
              </button>
              {error && (
                <p className="text-xs font-medium text-rose-300/80">
                  <span className="font-semibold">Heads-up:</span> {error}
                </p>
              )}
            </div>
          </div>
        </section>

        <section className="grid gap-8 xl:grid-cols-[1.6fr,1fr]">
          <div className="rounded-3xl border border-sky-500/20 bg-slate-900/60 p-8">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs uppercase tracking-[0.35em] text-slate-400">
                  Tool Library
                </p>
                <h2 className="text-2xl font-semibold text-slate-50">
                  Activate the operators to support this run
                </h2>
              </div>
              <PanelTop className="h-8 w-8 text-sky-300" />
            </div>
            <div className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-2">
              {availableTools.map((tool) => (
                <ToolCard
                  key={tool.id}
                  tool={tool}
                  active={tool.isActive}
                  onToggle={toggleTool}
                />
              ))}
            </div>
          </div>

          <div className="flex flex-col gap-6 rounded-3xl border border-sky-500/20 bg-slate-900/60 p-8">
            <div className="flex items-center gap-3">
              <div className="grid h-12 w-12 place-items-center rounded-2xl bg-sky-500/20 text-sky-200">
                <BrainCircuit className="h-7 w-7" />
              </div>
              <div>
                <p className="text-xs uppercase tracking-[0.35em] text-slate-400">
                  Stage Telemetry
                </p>
                <h2 className="text-2xl font-semibold text-slate-50">Execution timeline</h2>
              </div>
            </div>
            <div className="space-y-4">
              {STAGES.map((stage) => {
                const status = stageStates[stage.id];
                return (
                  <motion.div
                    key={stage.id}
                    layout
                    className={cn(
                      "rounded-2xl border p-5 transition",
                      status === "pending" && "border-slate-700/60 bg-slate-900/70",
                      status === "active" && "border-sky-400/50 bg-slate-900/90 shadow-focus",
                      status === "complete" && "border-emerald-400/40 bg-slate-900/80"
                    )}
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className="grid h-10 w-10 place-items-center rounded-xl bg-sky-500/15 text-sky-200">
                          {status === "complete" ? (
                            <Bot className="h-5 w-5" />
                          ) : status === "active" ? (
                            <Loader2 className="h-5 w-5 animate-spin" />
                          ) : (
                            <Sparkles className="h-5 w-5" />
                          )}
                        </div>
                        <div>
                          <p className="text-xs uppercase tracking-[0.35em] text-slate-400">
                            {stage.label}
                          </p>
                          <p className="text-sm font-semibold text-slate-100">
                            {stage.description}
                          </p>
                        </div>
                      </div>
                      <span
                        className={cn(
                          "text-xs font-semibold uppercase tracking-[0.35em]",
                          status === "pending" && "text-slate-500",
                          status === "active" && "text-sky-300",
                          status === "complete" && "text-emerald-300"
                        )}
                      >
                        {status}
                      </span>
                    </div>
                    <AnimatePresence mode="wait">
                      {stageOutputs[stage.id] && (
                        <motion.p
                          key={stageOutputs[stage.id]}
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0, y: -10 }}
                          transition={{ duration: 0.25 }}
                          className="mt-3 text-sm text-slate-300/90"
                        >
                          {stageOutputs[stage.id]}
                        </motion.p>
                      )}
                    </AnimatePresence>
                  </motion.div>
                );
              })}
            </div>
          </div>
        </section>

        <section className="rounded-3xl border border-sky-500/20 bg-slate-900/60 p-8">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div>
              <p className="text-xs uppercase tracking-[0.35em] text-slate-400">
                Mission Debrief
              </p>
              <h2 className="text-2xl font-semibold text-slate-50">
                Review previous autonomous executions
              </h2>
            </div>
            <div className="rounded-full border border-sky-500/20 bg-slate-900/60 px-4 py-2 text-xs uppercase tracking-[0.3em] text-slate-400">
              <span className="text-sky-200">{missionLog.length}</span> Missions Logged
            </div>
          </div>
          <div className="mt-6 grid gap-4 md:grid-cols-2">
            <AnimatePresence>
              {missionLog.map((log) => (
                <motion.article
                  key={log.id}
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -12 }}
                  className="flex h-full flex-col gap-4 rounded-2xl border border-sky-500/20 bg-slate-900/80 p-6"
                >
                  <div className="flex items-center justify-between gap-3">
                    <div>
                      <p className="text-xs uppercase tracking-[0.35em] text-slate-400">
                        {log.mission}
                      </p>
                      <p className="mt-1 text-sm text-slate-300/90">{log.objective}</p>
                    </div>
                    <span className="rounded-full border border-sky-400/30 px-3 py-1 text-xs font-semibold uppercase tracking-[0.3em] text-sky-200">
                      {Math.round(log.duration / 1000)}s
                    </span>
                  </div>
                  <p className="text-sm text-slate-200/90">{log.result}</p>
                  <div className="flex flex-wrap gap-2 text-xs text-slate-300/90">
                    {log.tools.map((toolId) => {
                      const tool = TOOL_LIBRARY.find((item) => item.id === toolId);
                      return (
                        <span
                          key={toolId}
                          className="rounded-full border border-sky-400/20 bg-slate-900/80 px-3 py-1 text-xs font-medium"
                        >
                          {tool?.name ?? toolId}
                        </span>
                      );
                    })}
                  </div>
                </motion.article>
              ))}
            </AnimatePresence>

            {missionLog.length === 0 && (
              <div className="col-span-full rounded-2xl border border-dashed border-sky-300/30 bg-slate-900/50 p-10 text-center text-sm text-slate-400">
                <p className="flex items-center justify-center gap-2 text-slate-300">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Agent telemetry will populate here after your first launch.
                </p>
              </div>
            )}
          </div>
        </section>
      </div>
    </main>
  );
}
